# Prometheus configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node_export"
    static_configs:
      - targets: ["target-server-ip:9100", "target-server-ip:9100", "target-server-ip:9100"]
  - job_name: 'cadvisor'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['target-server-ip:9091', 'target-server-ip:9091', 'target-server-ip:9091']
